/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numerical_second_hw;
import java.lang.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Third_Question extends javax.swing.JFrame {

    /**
     * Creates new form Third_Question
     */
    public Third_Question() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aa = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        cc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Third Question :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("       a0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("        a1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("        a2");

        aa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        aa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        aa.setEnabled(false);
        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });

        bb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bb.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bb.setEnabled(false);
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });

        cc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cc.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Previous Question ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aa, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(bb)
                            .addComponent(cc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aa, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bb, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cc, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public double calc_sum_x1i_or_sum_x2i_or_sum_yi (double []a,int n){
        double r=0;
        for(int i=0;i<n;i++){
        r+=a[i];}
        
        return r;
    }
     
     public double calc_sum_x1i2_or_sum_x2i2 (double []a,int n){
        double r=0;
        for(int i=0;i<n;i++){
        r+=a[i]*a[i];}

        return r;
    }
    
     public double calc_sum_x1i_x2i_or_sum_x1i_yi_or_sum_x2i_yi (double []a,double []b,int n){
        double r=0;
        for(int i=0;i<n;i++){
        r+=a[i]*b[i];}
        
        return r;
    }
    
     
     public double calc_a0(double sum_yi,double a1,double sum_x1i,double a2,double sum_x2i,int n){
         double z;
         z=(sum_yi-(a1*sum_x1i)-(a2*sum_x2i))/n;
         return z;
   
     }
     
      public double calc_a1(double sum_x1i_yi,double a0,double sum_x1i,double a2,double sum_x1i_x2i,double sum_x1i2){
         double z;
         z=(sum_x1i_yi-(a0*sum_x1i)-(a2*sum_x1i_x2i))/sum_x1i2;
         return z;
   
     }
      
       public double calc_a2(double sum_x2i_yi,double a0,double sum_x2i,double a1,double sum_x1i_x2i,double sum_x2i2){
         double z;
         z=(sum_x2i_yi-(a0*sum_x2i)-(a1*sum_x1i_x2i))/sum_x2i2;
         return z;
   
     }
     
     
    
    
    
    
    
    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aaActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int n;
    n=25;
    double x1[]=new double[n];
    double x2[]=new double [n];
    double y[]=new double [n];
    double a0=0;
    double a1=0;
    double a2=0;
    double sum_x1i=0;
    double sum_x2i=0;
    double sum_x1i2=0;
    double sum_x2i2=0;
    double sum_x1i_x2i=0;
    double sum_yi=0;
    double sum_x1i_yi=0;
    double sum_x2i_yi=0;
    double num_of_iter=1000000;
    
    
    x1[0]=1.00;
    x1[1]=2.00;
    x1[2]=3.00;
    x1[3]=4.00;
    x1[4]=5.00;
    x1[5]=6.00;
    x1[6]=7.00;
    x1[7]=8.00;
    x1[8]=9.00;
    x1[9]=10.00;
    x1[10]=11.00;
    x1[11]=12.00;
    x1[12]=13.00;
    x1[13]=14.00;
    x1[14]=15.00;
    x1[15]=16.00;
    x1[16]=17.00;
    x1[17]=18.00;
    x1[18]=19.00;
    x1[19]=20.00;
    x1[20]=21.00;
    x1[21]=22.00;
    x1[22]=23.00;
    x1[23]=24.00;
    x1[24]=25.00;
    
    x2[0]=0.50;
    x2[1]=3.76;
    x2[2]=7.28;
    x2[3]=9.65;
    x2[4]=13.04;
    x2[5]=16.14;
    x2[6]=19.23;
    x2[7]=22.33;
    x2[8]=25.43;
    x2[9]=28.53;
    x2[10]=31.62;
    x2[11]=34.72;
    x2[12]=37.82;
    x2[13]=40.91;
    x2[14]=44.01;
    x2[15]=47.11;
    x2[16]=50.20;
    x2[17]=53.30;
    x2[18]=56.40;
    x2[19]=59.50;
    x2[20]=62.59;
    x2[21]=65.69;
    x2[22]=68.79;
    x2[23]=71.88;
    x2[24]=74.98;
    
    y[0]=3.964;
    y[1]=5.627;
    y[2]=7.294;
    y[3]=8.944;
    y[4]=10.609;
    y[5]=12.269;
    y[6]=13.930;
    y[7]=15.591;
    y[8]=17.251;
    y[9]=18.912;
    y[10]=20.572;
    y[11]=22.233;
    y[12]=23.894;
    y[13]=25.554;
    y[14]=27.215;
    y[15]=28.875;
    y[16]=30.536;
    y[17]=32.197;
    y[18]=33.857;
    y[19]=35.518;
    y[20]=37.178;
    y[21]=38.839;
    y[22]=40.500;
    y[23]=42.160;
    y[24]=43.821;
    
    
    sum_x1i=calc_sum_x1i_or_sum_x2i_or_sum_yi (x1,n);
    sum_x2i=calc_sum_x1i_or_sum_x2i_or_sum_yi (x2,n);
    sum_x1i2=calc_sum_x1i2_or_sum_x2i2 (x1,n);
    sum_x2i2=calc_sum_x1i2_or_sum_x2i2 (x2,n);
    sum_x1i_x2i=calc_sum_x1i_x2i_or_sum_x1i_yi_or_sum_x2i_yi (x1,x2,n);
    sum_yi=calc_sum_x1i_or_sum_x2i_or_sum_yi (y,n);
    sum_x1i_yi=calc_sum_x1i_x2i_or_sum_x1i_yi_or_sum_x2i_yi (x1,y,n);
    sum_x2i_yi=calc_sum_x1i_x2i_or_sum_x1i_yi_or_sum_x2i_yi (x2,y,n);

    while(true){
        if(num_of_iter<=0){
        break;}
        
        a0=calc_a0(sum_yi,a1,sum_x1i,a2,sum_x2i,n);
        a1=calc_a1(sum_x1i_yi,a0,sum_x1i,a2,sum_x1i_x2i,sum_x1i2);
        a2=calc_a2(sum_x2i_yi,a0,sum_x2i,a1,sum_x1i_x2i,sum_x2i2);
        
        num_of_iter--;
      
    }
    
   aa.setText(a0+"");
   bb.setText(a1+"");
   cc.setText(a2+"");

   label.setText("The Equation is : Y = "+a0+"+"+a1+"x1"+"+"+a2+"x2");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.dispose();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Second_Question v=new Second_Question();
this.dispose();
v.setVisible(true);        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Third_Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aa;
    private javax.swing.JTextField bb;
    private javax.swing.JTextField cc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
